### ISSUE TITLE
gnssserver - nmea message communication bug

### ISSUE THREAD

**Issue by sergiobellido** [semuconsulting/pygnssutils#14]
**Describe the bug**

I am trying to communicate gps data serial port through TCP/IP with gnsserver CLI. when I try to connect to server socket, this error is raised: "TypeError: a bytes-like object is required, not 'NMEAMessage'"
Traceback: 
```
Exception occurred during processing of request from ('127.0.0.1', 61299)
Traceback (most recent call last):
  File "C:\Users\g512\anaconda3\envs\generic\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\g512\anaconda3\envs\generic\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\g512\anaconda3\envs\generic\lib\site-packages\pygnssutils\socket_server.py", line 220, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\g512\anaconda3\envs\generic\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\g512\anaconda3\envs\generic\lib\site-packages\pygnssutils\socket_server.py", line 291, in handle
    self._write_from_mq()
  File "C:\Users\g512\anaconda3\envs\generic\lib\site-packages\pygnssutils\socket_server.py", line 409, in _write_from_mq
    self.wfile.write(raw)
  File "C:\Users\g512\anaconda3\envs\generic\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'NMEAMessage'
```
pygnssutils version: 1.01

**To Reproduce**

Open anaconda prompt terminal and type this command:
`gnssserver ntripmode=0 inport=COM5 baudrate=38400 hostip=127.0.0.1 outport=50010 limit=0 format=1 verbosity=2`

On the other hand, when the socket is already created,  open a jupyter notebook and run this code: 
```
import socket
host = "127.0.0.1"
port = 50010
gps_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
gps_socket.connect((host, port))
response = gps_socket.recv(1024).decode('latin')
print(response)
```

**Expected Behaviour**

I suppose I will be reading gps data (nmea messages) through the socket like I did working with the graphical interface PyGPSClient. 

**Desktop (please complete the following information):**

- Operating system: Windows 10
- The type of serial connection: USB

**GNSS/GPS Device (please complete the following information as best you can):**

- Device Model/Generation: ZED-F9P module
- Firmware Version: 1.32

**Additional context**

I solved the problem by identifying if the message socket server is sending is a NMEA msg and then serializing it. Modified _**_write_from_mq()**_ function on socket_server.py script.
![Captura](https://user-images.githubusercontent.com/56564192/215774070-3a0e6244-9dcd-4b52-83c3-5cab6dd8130d.JPG)

I would like you to fix the bug. 
Thanks,

**Comment by semuadmin** [comment]
Hi @sergiobellido 

Did this help at all?

FYI the `pygnssutils` library is being updated shortly to use the standard Python `argparse` argument parser library, so the CLI command arguments will change to the new format, e.g.

```
gnssserver ntripmode=0 inport=COM5 baudrate=38400 hostip=127.0.0.1 outport=50010 limit=0 format=2 verbosity=2
```
will change in `pygnssutils>=1.0.2` to:
```
gnssserver --ntripmode 0 --inport COM5 --baudrate 38400 --hostip 127.0.0.1 --outport 50010 --limit 0 --format 2 --verbosity 2
```

But, as I say, if you use the default `gnssserver` format (2 = binary), you should find your server-client combination works OK.

If it doesn't, please get back to me.

**Comment by jonppe** [comment]
Hello, I come from the ffuuture!

At least I'd like to point out that this tip to use the format parameter still seems very valid since the default format for gnssstreamer (but not gnssserver) is 1 (i.e., NmeaObject).
gnsserver and gnssstreamer have so many inputs and outputs it's easy miss that the format parameter even affects the TCP output.

Also I don't actually quite understand how gnssstreamer even could work with some of the formats, at least when the output is socket. There doesn't seem to be any handshakes with the client and the stack trace seems to hint there gnssstreamer tries to output in wrong format (i.e., the capabilities of the TCP-client should not affect or maybe I understood your previous point wrong):

2025-02-14 10:10:25.9 - ERROR - pygnssutils.socket_server - Client error ('127.0.0.1', 39724) <socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 50011), raddr=('127.0.0.1', 39724)>
Exception in thread Thread-5 (process_request_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/atle/sinko/lib/pygnssutils/src/pygnssutils/socket_server.py", line 282, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/atle/sinko/lib/pygnssutils/src/pygnssutils/socket_server.py", line 346, in handle
    self._write_from_mq()
  File "/home/atle/sinko/lib/pygnssutils/src/pygnssutils/socket_server.py", line 509, in _write_from_mq
    self.wfile.write(raw)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'

And depending on the format, the last line maybe also:
TypeError: a bytes-like object is required, not 'NMEAMessage'
or something else.

I guess I'm fine with just using --format 2 but I'm thinking should the default format also for gnssstreamer to be changed or something... Although, I haven't yet really analyzed the differences between the server and the streamer and whether I should actually use the other.
